site_name: LLM Semantic Router
site_description: Intelligent Mixture-of-Models Router using Envoy ExtProc for LLM Applications
site_author: Semantic Router Team
repo_name: redhat-et/semantic_route
repo_url: https://github.com/redhat-et/semantic_route
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.annotate

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

plugins:
  - search

nav:
  - Home: index.md
  - Overview:
      - Semantic Router Overview: overview/semantic-router-overview.md
      - Why Mixture of Models?: overview/mixture-of-models.md
  - Architecture:
      - System Architecture: architecture/system-architecture.md
      - Envoy ExtProc Integration: architecture/envoy-extproc.md
      - Router Implementation: architecture/router-implementation.md
  - Model Training:
      - Training Overview: training/training-overview.md
      - Classification Models: training/classification-models.md
      - Datasets and Purposes: training/datasets.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
      - Configuration: getting-started/configuration.md
  - API Reference:
      - Router API: api/router.md
      - Classification API: api/classification.md
