bert_model:
  model_id: sentence-transformers/all-MiniLM-L12-v2
  threshold: 0.6
  use_cpu: true

# Classifier configuration for text classification
classifier:
  model_id: "classifier_model_fine_tuning/category_classifier_linear_model"
  threshold: 0.7
  use_cpu: true
  category_mapping_path: "config/category_mapping.json"

semantic_cache:
  enabled: true
  similarity_threshold: 0.8
  max_entries: 1000
  ttl_seconds: 3600
categories:
- name: business
  models:
  - phi4
  - gemma3
  - mistral-small3.1
- name: law
  models:
  - gemma3
  - phi4
  - mistral-small3.1
- name: psychology
  models:
  - mistral-small3.1
  - gemma3
  - phi4
- name: biology
  models:
  - mistral-small3.1
  - gemma3
  - phi4
- name: chemistry
  models:
  - mistral-small3.1
  - gemma3
  - phi4
- name: history
  models:
  - mistral-small3.1
  - phi4
  - gemma3
- name: other
  models:
  - gemma3
  - phi4
  - mistral-small3.1
- name: health
  models:
  - gemma3
  - phi4
  - mistral-small3.1
- name: economics
  models:
  - gemma3
  - mistral-small3.1
  - phi4
- name: math
  models:
  - phi4
  - mistral-small3.1
  - gemma3
- name: physics
  models:
  - gemma3
  - phi4
  - mistral-small3.1
- name: computer science
  models:
  - gemma3
  - mistral-small3.1
  - phi4
- name: philosophy
  models:
  - phi4
  - gemma3
  - mistral-small3.1
- name: engineering
  models:
  - gemma3
  - mistral-small3.1
  - phi4
default_model: mistral-small3.1
