name: Nightly Tests

on:
  schedule:
    # Run nightly at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  nightly-test:
    runs-on:
      labels: ubuntu-20.04-16core
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.85

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          make \
          build-essential \
          pkg-config

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          candle-binding/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}

    - name: Cache Go dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Build Rust library
      run: make rust

    - name: Install HuggingFace CLI
      run: |
        pip install -U "huggingface_hub[cli]"

    - name: Download models
      run: make download-models

    - name: Run semantic router tests
      run: make test-semantic-router
      env:
        CGO_ENABLED: 1
        LD_LIBRARY_PATH: ${{ github.workspace }}/candle-binding/target/release

    - name: Upload test artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: |
          **/*.log
          **/test-output.*
        retention-days: 7

    - name: Notify on failure
      if: failure()
      run: |
        echo "::error::Nightly tests failed. Check the workflow run for details."
